version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_1303_AZPPProject
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: SIQA_kvv_wm_io
  gitUrl: https://github.webmethods.io/mjan
  gitUsername: kvv
  gitBranch: main
services:
- serviceName: project.siqa_1303_azpp.integrations:tpp
  packages:
  - name: SIQA_1303_AZPPProject
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.32
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: SIQAJDBCAdapterTests.adapterServices:getData
  packages:
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.32
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
